server:
  port: 8851

spring:
  application:
    name: user-center
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
        cluster-name: BJ
    sentinel:
      #filter:
      #关闭对 springMVC 端点的保护， 防止干扰
      #enabled: false
      transport:
        # 指定sentinel控制台地址
        dashboard: localhost:8080
        # 指定和控制台通信的IP，若不配置，会自动选择一个IP注册
        #client-ip: 127.0.0.1
        # 指定和控制台通信的端口，默认值8719
        # 若不配置，会自动扫猫从8719开始扫猫，依次+1，直到找到未被占用的端口
        #port: 8719
        # 心跳发送周期，默认值null
        # 但在SimpleHttpHeartbeatSender会用默认值10秒
        #heartbeat-interval-ms: 10000
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        output:
          # 用来指定topic
          destination: stream-test-topic



  datasource:
    password: root2018
    username: root
    url: jdbc:mysql://localhost:3306/user-center?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://127.0.0.1:9411
    #解决nacos把http://127.0.0.1:9411当做服务，而一直刷新本地缓存但是找不到而报错的问题
    #这是discoveryClientEnabled是zipkin底层代码中指定的参数，SR3版本会解决，到时候可以直接使用discovery.clintnt.enabled : false
    discoveryClientEnabled: false

  sleuth:
    sampler:
      # 抽样率，默认是0.1(百分之90会被丢弃，为了减少对应用性能的影响)，此处便于测试才设置成了1.0(百分之百)
      probability: 1.0

#配置某服务的负载均衡的规则
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.itczy.org.ribbonConfiguration.NacosWeightRule

#ribbon设置饥饿加载，clients用于指定具体服务，多个用逗号隔开
ribbon:
  eager-load:
    enabled: true
    clients: user-center

# RestTemplate的senetinel开关，用于开启或关闭@SentinelRestTemplate，默认开启
resttemplate:
  sentinel:
    enabled: false

# feign的senetinel开关，用于开启或关闭@SentinelRestTemplate，默认开启
feign:
  sentinel:
    enabled: false

#rocketmq服务
rocketmq:
  name-server: 127.0.0.1:9876

logging:
  level:
    com.alibaba.nacos: error

mybatis:
  configuration:
    # 开启mybatis将数据下划线命名映射成对应驼峰命名的字段
    map-underscore-to-camel-case: true
