server:
  port: 8851

spring:
  application:
    name: user-center
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
        cluster-name: BJ
  datasource:
    password: root2018
    username: root
    url: jdbc:mysql://localhost:3306/user-center?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#ribbon设置饥饿加载，clients用于指定具体服务，多个用逗号隔开
ribbon:
  eager-load:
    enabled: true
    clients: user-center

