server:
  port: 8861

spring:
  application:
    name: content-center
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
        cluster-name: BJ
    sentinel:
      transport:
        # 指定sentinel控制台地址
        dashboard: localhost:8080
        # 指定和控制台通信的IP，若不配置，会自动选择一个IP注册
        #client-ip: 127.0.0.1
        # 指定和控制台通信的端口，默认值8719
        # 若不配置，会自动扫猫从8719开始扫猫，依次+1，直到找到未被占用的端口
        #port: 8719
        # 心跳发送周期，默认值null
        # 但在SimpleHttpHeartbeatSender会用默认值10秒
        #heartbeat-interval-ms: 10000

#配置某服务的负载均衡的规则
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.itczy.org.configuration.NacosWeightRule

