server:
  port: 8040

spring:
  application:
    name: gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他微服务
          enables: true

#actuator配置
management:
  endpoints:
    web:
      exposure:
        incode: '*'
  endpoint:
    health:
      show-details: always